name = "SpinGlassMPS"
uuid = "c2f5b427-f156-4e34-b195-1177e6ada83e"
authors = ["Bartłomiej Gardas <bartek.gardas@gmail.com>", "Konrad Jałowiecki <dexter2206@gmail.com>", "Łukasz Pawela <lukasz.pawela@gmail.com>", "Marek M. Rams <marekrams@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SpinGlassNetworks = "b7f6bd3e-55dc-4da6-96a9-ef9dbec6ac19"
SpinGlassTensors = "7584fc6a-5a23-4eeb-8277-827aab0146ea"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
DocStringExtensions = "0.9"
ProgressMeter = "1.10"
SpinGlassNetworks = "1.1.2"
SpinGlassTensors = "1.1.1"
TensorCast = "0.4"
TensorOperations = "4"
julia = "1.9, 1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]