name = "SpinGlassMPS"
uuid = "c2f5b427-f156-4e34-b195-1177e6ada83e"
authors = ["Bartłomiej Gardas <bartek.gardas@gmail.com>", "Konrad Jałowiecki <dexter2206@gmail.com>", "Łukasz Pawela <lukasz.pawela@gmail.com>", "Marek M. Rams <marekrams@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LabelledGraphs = "605abd48-4d17-4660-b914-d4df33194460"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SpinGlassNetworks = "b7f6bd3e-55dc-4da6-96a9-ef9dbec6ac19"
SpinGlassTensors = "7584fc6a-5a23-4eeb-8277-827aab0146ea"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
DocStringExtensions = "0.9"
Graphs = "1.11"
LabelledGraphs = "0.4"
Memoization = "0.2"
MetaGraphs = "0.7"
ProgressMeter = "1.10"
SpinGlassNetworks = "1.1.2"
SpinGlassTensors = "1.1.1"
TensorCast = "0.4"
TensorOperations = "4"
julia = "1.9, 1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
